/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ElAside: typeof import('element-plus/es')['ElAside']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElTreeV2: typeof import('element-plus/es')['ElTreeV2']
    FileNameTable: typeof import('./src/components/FileNameTable/FileNameTable.vue')['default']
    FileNameTableSelector: typeof import('./src/components/FileNameTable/FileNameTableSelector.vue')['default']
    FileTree: typeof import('./src/components/FileTree.vue')['default']
    HoverBubble: typeof import('./src/components/HoverBubble.vue')['default']
    Menu: typeof import('./src/components/Menu.vue')['default']
    PakFileItem: typeof import('./src/components/PakFileItem.vue')['default']
    PakFiles: typeof import('./src/components/PakFiles.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Settings: typeof import('./src/components/Settings/Settings.vue')['default']
    SettingsItem: typeof import('./src/components/Settings/SettingsItem.vue')['default']
    SettingsItemSwitch: typeof import('./src/components/Settings/SettingsItemSwitch.vue')['default']
    UpdateDialog: typeof import('./src/components/UpdateDialog.vue')['default']
  }
  export interface ComponentCustomProperties {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
