/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ElAside: typeof import('element-plus/es')['ElAside']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElText: typeof import('element-plus/es')['ElText']
    ElTreeV2: typeof import('element-plus/es')['ElTreeV2']
    FileNameTableSelector: typeof import('./src/components/FileNameTableSelector.vue')['default']
    FileTree: typeof import('./src/components/FileTree.vue')['default']
    PakFileItem: typeof import('./src/components/PakFileItem.vue')['default']
    PakFiles: typeof import('./src/components/PakFiles.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
  export interface ComponentCustomProperties {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
