/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import { GlobalComponents } from 'vue'

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ElAside: typeof import('element-plus/es')['ElAside']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElImage: typeof import('element-plus/es')['ElImage']
    ElTreeV2: typeof import('element-plus/es')['ElTreeV2']
    FileConflict: typeof import('./src/components/FileConflict.vue')['default']
    FileNameTable: typeof import('./src/components/FileNameTable/FileNameTable.vue')['default']
    FileNameTableSelector: typeof import('./src/components/FileNameTable/FileNameTableSelector.vue')['default']
    FileTree: typeof import('./src/components/FileTree.vue')['default']
    HoverBubble: typeof import('./src/components/HoverBubble.vue')['default']
    Menu: typeof import('./src/components/Menu.vue')['default']
    PakFileItem: typeof import('./src/components/PakFileItem.vue')['default']
    PakFiles: typeof import('./src/components/PakFiles.vue')['default']
    PathScanner: typeof import('./src/components/tools/PathScanner.vue')['default']
    PreviewPane: typeof import('./src/components/PreviewPane.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Settings: typeof import('./src/components/Settings/Settings.vue')['default']
    SettingsItem: typeof import('./src/components/Settings/SettingsItem.vue')['default']
    SettingsItemSwitch: typeof import('./src/components/Settings/SettingsItemSwitch.vue')['default']
    SplitPanel: typeof import('./src/components/SplitPanel.vue')['default']
    UpdateDialog: typeof import('./src/components/UpdateDialog.vue')['default']
  }
}

// For TSX support
declare global {
  const ElAside: typeof import('element-plus/es')['ElAside']
  const ElContainer: typeof import('element-plus/es')['ElContainer']
  const ElImage: typeof import('element-plus/es')['ElImage']
  const ElTreeV2: typeof import('element-plus/es')['ElTreeV2']
  const FileConflict: typeof import('./src/components/FileConflict.vue')['default']
  const FileNameTable: typeof import('./src/components/FileNameTable/FileNameTable.vue')['default']
  const FileNameTableSelector: typeof import('./src/components/FileNameTable/FileNameTableSelector.vue')['default']
  const FileTree: typeof import('./src/components/FileTree.vue')['default']
  const HoverBubble: typeof import('./src/components/HoverBubble.vue')['default']
  const Menu: typeof import('./src/components/Menu.vue')['default']
  const PakFileItem: typeof import('./src/components/PakFileItem.vue')['default']
  const PakFiles: typeof import('./src/components/PakFiles.vue')['default']
  const PathScanner: typeof import('./src/components/tools/PathScanner.vue')['default']
  const PreviewPane: typeof import('./src/components/PreviewPane.vue')['default']
  const RouterLink: typeof import('vue-router')['RouterLink']
  const RouterView: typeof import('vue-router')['RouterView']
  const Settings: typeof import('./src/components/Settings/Settings.vue')['default']
  const SettingsItem: typeof import('./src/components/Settings/SettingsItem.vue')['default']
  const SettingsItemSwitch: typeof import('./src/components/Settings/SettingsItemSwitch.vue')['default']
  const SplitPanel: typeof import('./src/components/SplitPanel.vue')['default']
  const UpdateDialog: typeof import('./src/components/UpdateDialog.vue')['default']
}